### ISSUE TITLE
Navigation for each project 😏

### ISSUE THREAD

**Issue by jhonatadev** [allonsmandy/origamid-projetos#1]
You could create something with ajax, such as having a main **index** to go through each project without having to go to the project folder, making life easier. :)

An example would be like this

![Anotação 2019-08-21 170852](https://user-images.githubusercontent.com/40447114/63465081-d9087900-c436-11e9-90ab-15764b875ca3.png)

**Comment by allonsmandy** [comment]
nossa que chique escrevendo inglês

**Comment by allonsmandy** [comment]
muchas gracias por tu contribución, pensaré en esto :3

**Comment by allonsmandy** [comment]
> You could create something with ajax, such as having a main ** index ** to go through each project without having to go to the project folder, making life easier. :)
> 
> An example would be like this
> 
> ![Anotação 2019-08-21 170852](https://user-images.githubusercontent.com/40447114/63465081-d9087900-c436-11e9-90ab-15764b875ca3.png)
